rule:
  global:
    indent_size: 4
  constant_004:
    case: 'upper'
  type_500:
    case: 'upper'
  process_017:
    case: 'upper'
  process_019:
    case: 'upper'
  generate_005:
    case: 'upper'
  generate_012:
    case: 'upper'
  process_022:
    style: no_blank_line
  case_009:
    style: no_blank_line
  case_200:
    style: no_blank_line
  case_201:
    style: no_blank_line
  subprogram_body_201:
    style: no_blank_line
  subprogram_body_202:
    style: no_blank_line
  subprogram_body_203:
    style: no_blank_line
  subprogram_body_204:
    style: no_blank_line
  generic_007:
    case: 'upper'
  conditional_waveforms_001:
    allow_single_line: "yes"
  if_030:
    disable: true    
  if_031:
    disable: true
  whitespace_011:
    disable: true

